name: Auto Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点自动运行
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: LibreSpark/LibreTV
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Mirror changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git remote add fork https://github.com/${{ github.repository }}
          git push fork HEAD:main --force
